import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=fileURLToPath(new URL('../../../',import.meta.url)),evidence=root+'games/river-expedition/docs/';mkdirSync(evidence,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const checks=[],errors=[],network=[];
try{
 const ctx=await browser.newContext({viewport:{width:1366,height:768},offline:true});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
 await page.goto(pathToFileURL(root+'dist/River-Expedition-James-River.html').href);await page.waitForTimeout(150);assert.deepEqual(errors,[]);await page.screenshot({path:evidence+'v11-title.png',fullPage:true});await page.locator('#launch').click();assert.equal(await page.evaluate(()=>expedition.phase),'title');const introProgress=await page.evaluate(()=>expedition.progress);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>expedition.progress),introProgress);assert.equal(await page.locator('[data-example]').count(),3);await page.screenshot({path:evidence+'v11-intro.png',fullPage:true});await page.locator('#introNext').click();assert.equal(await page.evaluate(()=>expedition.phase),'title');await page.screenshot({path:evidence+'v11-intro-questions.png',fullPage:true});await page.locator('#beginRun').click();
 assert(await page.locator('#touchControls').isHidden());assert((await page.locator('#hearts').getAttribute('aria-label')).includes('5 of 5'));
 await page.locator('#mapButton').click();assert.equal(await page.locator('#place-jamestown').count(),0);assert.equal(await page.locator('#place-richmond').count(),0);await page.locator('#back').click();checks.push('No future map locations revealed at launch; desktop control pad hidden');
 const x=await page.evaluate(()=>expedition.x);await page.keyboard.down('ArrowRight');await page.waitForTimeout(350);await page.keyboard.up('ArrowRight');assert((await page.evaluate(()=>expedition.x))>x+25);const box=await page.locator('#game').boundingBox();await page.mouse.move(box.x+box.width*.4,box.y+box.height*.7);await page.mouse.down();await page.waitForTimeout(200);await page.mouse.up();checks.push('Live keyboard and mouse steering');
 await page.evaluate(()=>{expedition.invulnerable=0;expedition.health=5;expedition.hazards=[{s:expedition.progress+2,x:expedition.x,kind:'rock',radius:12}];});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>expedition.health),4);assert((await page.locator('#hearts').getAttribute('aria-label')).includes('4 of 5'));await page.screenshot({path:evidence+'v11-heart-loss.png',fullPage:true});
 await page.evaluate(()=>{expedition.invulnerable=0;expedition.health=1;expedition.hazards=[{s:expedition.progress+2,x:expedition.x,kind:'rock',radius:12}];});await page.locator('#recover').waitFor();assert.equal(await page.evaluate(()=>expedition.health),0);await page.locator('#recover').click();assert.equal(await page.evaluate(()=>expedition.health),5);checks.push('Visible heart loss, zero-heart repair screen, protected recovery');
 await page.locator('#pauseButton').click();const paused=await page.evaluate(()=>expedition.progress);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>expedition.progress),paused);await page.locator('#resume').click();
 await page.evaluate(()=>{expedition.invulnerable=4;expedition.health=3;expedition.hazards=[];expedition.pickups=[{id:'test-heart',s:expedition.progress+100,x:expedition.x,collected:false}];});await page.screenshot({path:evidence+'v11-powerup.png',fullPage:true});await page.evaluate(()=>{expedition.pickups[0].s=expedition.progress+2;});await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>expedition.health),4);assert.equal(await page.evaluate(()=>expedition.pickups[0].collected),true);await page.evaluate(()=>{expedition.health=5;expedition.pickups=[{id:'full-heart',s:expedition.progress+2,x:expedition.x,collected:false}];});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>expedition.health),5);checks.push('Collectible heart restores one, is consumed once, and cannot exceed maximum');
 const seed=await page.evaluate(()=>expedition.seed),hazards=await page.evaluate(()=>JSON.stringify(makeHazards(LEVEL.legs[0],expedition.seed)));
 for(let stop=0;stop<4;stop++){
  await page.evaluate(()=>{const l=currentLeg(expedition);expedition.progress=l.length-56;expedition.x=l.mode==='walk'?trailX(l,expedition.progress):riverProfile(l,expedition.progress).left+20;expedition.hazards=[];});
  
  await page.locator('#beginDockQuestions').waitFor({timeout:5000});assert.equal(await page.locator('[data-choice]').count(),0);if(stop===0)await page.screenshot({path:evidence+'v11-dock-map.png',fullPage:true});await page.locator('#beginDockQuestions').click();assert.equal(await page.evaluate(()=>expedition.phase),'checkpoint');assert.equal(await page.evaluate(()=>expedition.visited.length),stop+1);assert.equal(await page.evaluate(()=>expedition.health),5);
  if(stop===0){await page.screenshot({path:evidence+'v11-dock-question.png',fullPage:true});assert.deepEqual(await page.evaluate(()=>revealedPlaces().map(p=>p.id)),['bay','jamestown']);}
  for(const stage of ['dock','camp']){
   for(let i=0;i<5;i++){
    assert.equal(await page.evaluate(()=>review.stage),stage);assert.equal(await page.evaluate(()=>review.index),i);
    if(i===0){const wrong=await page.evaluate(()=>reviewQuestion(review).choices.find(c=>c.id!==reviewQuestion(review).correct).id);await page.locator(`[data-choice="${wrong}"]`).click();await page.locator('#retryQuestion').waitFor();assert.equal(await page.locator('[data-choice]').count(),0);assert.equal(await page.locator('#hintText').textContent(),await page.evaluate(()=>reviewQuestion(review).hint));assert.notEqual(await page.locator('#hintText').textContent(),await page.evaluate(()=>reviewQuestion(review).explanation));assert.equal(await page.evaluate(()=>review.index),i);if(stop===0&&stage==='dock')await page.screenshot({path:evidence+'v11-hint.png',fullPage:true});await page.locator('#retryQuestion').click();assert.equal(await page.locator('[data-choice]:not(:disabled)').count(),4);assert(await page.locator('#reviewNext').isHidden());assert.equal(await page.evaluate(()=>expedition.health),5);}
    if(i===0){const before=await page.evaluate(()=>JSON.stringify(review));if(stop===0&&stage==='dock'){assert(await page.locator('#questionJournal').isDisabled());}else{await page.locator('#questionJournal').click();assert.equal(await page.locator('.journal-entry').count(),stop+(stage==='camp'?1:0));assert(await page.locator('mark strong').count()>0);if(stop===0)await page.screenshot({path:evidence+'v11-reference.png',fullPage:true});await page.locator('#returnQuestion').click();}assert.equal(await page.evaluate(()=>JSON.stringify(review)),before);await page.locator('#questionMap').click();await page.locator('#place-jamestown').click();assert(await page.locator('#mapFact').isVisible());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>JSON.stringify(review)),before);}
    const correct=await page.evaluate(()=>reviewQuestion(review).correct);await page.locator(`[data-choice="${correct}"]`).click();if(i===0&&!(stop===0&&stage==='dock')){await page.locator('#questionJournal').click();await page.locator('#returnQuestion').click();assert.equal(await page.locator('[data-choice]:disabled').count(),4);assert(await page.locator('#reviewNext').isVisible());}await page.locator('#reviewNext').click();
   }
   if(stage==='dock'){assert.equal(await page.evaluate(()=>review.stage),'blurb');if(stop===0)await page.screenshot({path:evidence+'v11-field-note.png',fullPage:true});await page.locator('#reviewNext').click();}
  }
  assert.equal(await page.evaluate(()=>review),null);
  if(stop===0){await page.locator('#mapButton').click();assert(await page.locator('#place-jamestown').isVisible());assert.equal(await page.locator('#place-richmond').count(),0);await page.screenshot({path:evidence+'v11-discovered-map.png',fullPage:true});await page.locator('#back').click();}
 }
 assert.equal(await page.locator('.journal-entry').count(),4);await page.screenshot({path:evidence+'v11-complete.png',fullPage:true});checks.push('All four automatic landings from the opposite bank; dock map before each set; all 40 required correct answers; four intervening blurbs; non-answer hint dialogs and full-choice retries without heart penalties; progressive map reveal');
 await page.locator('#replay').click();assert.equal(await page.locator('#beginRun').count(),0);assert.equal(await page.evaluate(()=>expedition.phase),'play');for(const id of ['helpButton','mapButton','journalButton']){await page.locator('#'+id).click();await page.keyboard.press('Escape');assert(await page.locator('#overlay').isHidden());}assert.notEqual(await page.evaluate(()=>expedition.seed),seed);assert.notEqual(await page.evaluate(()=>JSON.stringify(expedition.hazards)),hazards);assert.equal(await page.evaluate(()=>expedition.visited.length),0);assert.equal(await page.evaluate(()=>expedition.notes.length),0);checks.push('Replay changes hazard seed/layout and clears discoveries');
 assert(await page.locator('.control-bar').isHidden());const end=await page.locator('.playfield').boundingBox();assert(end.y+end.height<=768);checks.push('Chromebook-sized playfield and HUD remain visible without persistent instructions');
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,offline:true});const mobile=await mobileContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));mobile.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await mobile.goto(page.url());await mobile.locator('#launch').tap();await mobile.screenshot({path:evidence+'v11-intro-touch.png',fullPage:true});await mobile.locator('#introNext').tap();await mobile.locator('#beginRun').tap();assert(await mobile.locator('#touchControls').isVisible());const before=await mobile.evaluate(()=>expedition.x);const b=await mobile.locator('[data-direction="right"]').boundingBox();const cdp=await mobileContext.newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await mobile.waitForTimeout(350);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForTimeout(100);assert((await mobile.evaluate(()=>expedition.x))>before+20);assert.equal(await mobile.locator('.held').count(),0);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.screenshot({path:evidence+'v11-touch.png',fullPage:true});checks.push('Touch controls default on for touch devices, steer, release, and fit without overflow');
 assert.deepEqual(errors,[]);assert.deepEqual(network,[]);const report={result:'PASS',version:'0.11.0',checks,errors,network,browser:await browser.version(),note:'Travel is accelerated between landings for UI testing. Model tests simulate full routes; questions are all exercised through UI.'};writeFileSync(evidence+'browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
