import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createExpedition,beginLeg,tick,riverProfile,trailX,advance,recover,currentLeg,makeHazards,makePickups,bump} from '../src/model.js';
import {createReview,reviewQuestion,answerReview,nextReview,dismissHint} from '../src/review.js';
const pack=JSON.parse(readFileSync(new URL('../content/james.json',import.meta.url)));
test('continuous steering and pause',()=>{const s=createExpedition(pack);beginLeg(s,0);const x=s.x;for(let i=0;i<60;i++)tick(s,{x:1},1/60);assert(s.x>x+70);assert(s.progress>50&&s.progress<80);s.phase='paused';const before=JSON.stringify(s);tick(s,{x:1,y:-1},1/60);assert.equal(JSON.stringify(s),before);});
test('one heart per impact, protection window, then recovery',()=>{const s=createExpedition(pack);beginLeg(s,0);s.hazards=[{s:1,x:s.x,kind:'rock',radius:12}];tick(s,{},1/60);assert.equal(s.health,4);tick(s,{},1/60);assert.equal(s.health,4);assert(s.slow>0);s.hazards=[];for(let i=0;i<150;i++)tick(s,{},1/60);assert.equal(s.slow,0);assert.equal(s.phase,'play');assert.equal(s.health,4);});
test('zero hearts pause for repair without discarding discoveries',()=>{const s=createExpedition(pack);beginLeg(s,0);s.notes=[{id:'kept'}];s.health=1;s.progress=500;bump(s,'Rock');assert.equal(s.phase,'rescue');assert.equal(s.health,0);const p=s.progress;tick(s,{},.05);assert.equal(s.progress,p);recover(s);assert.equal(s.health,5);assert.equal(s.phase,'play');assert.equal(s.progress,380);assert.equal(s.notes[0].id,'kept');assert.equal(s.invulnerable,4);});
test('crossing the line docks from either side without input, only once',()=>{for(const side of ['left','right']){const s=createExpedition(pack);beginLeg(s,0);const l=currentLeg(s);s.health=3;s.progress=l.length-55.1;s.x=riverProfile(l,s.progress)[side]+(side==='left'?20:-20);tick(s,{},1/60);assert.equal(s.phase,'docking');assert.deepEqual(s.visited,['tidal']);for(let i=0;i<60;i++)tick(s,{},1/60);assert.equal(s.phase,'checkpoint');assert.equal(s.health,5);assert.equal(s.progress,l.length);assert.deepEqual(s.visited,['tidal']);}});
test('water legs are longer and faster with reaction spacing preserved',()=>{const legs=pack.legs.filter(l=>l.mode==='boat');for(let i=1;i<legs.length;i++){assert(legs[i].length>legs[i-1].length);assert(legs[i].speed-legs[i].current>legs[i-1].speed-legs[i-1].current);}for(const l of legs){const h=makeHazards(l,17);for(let i=1;i<h.length;i++)assert(h[i].s-h[i-1].s>=(l.speed*1.4)-.001);}});
test('seed reproduces a run; different seeds vary placement',()=>{assert.deepEqual(makeHazards(pack.legs[0],123),makeHazards(pack.legs[0],123));assert.notDeepEqual(makeHazards(pack.legs[0],123),makeHazards(pack.legs[0],456));});
test('every route is reachable continuously, with repair when necessary',()=>{const s=createExpedition(pack,true,234);beginLeg(s,0);for(let index=0;index<4;index++){let guard=0;const l=currentLeg(s);while(s.phase!=='checkpoint'&&guard++<60000){if(s.phase==='rescue')recover(s);const target=l.mode==='walk'?trailX(l,s.progress):riverProfile(l,s.progress).center;tick(s,{x:Math.max(-1,Math.min(1,(target-s.x)/8)),y:l.mode==='walk'?-1:0},1/60);}assert.equal(s.phase,'checkpoint');advance(s);}assert.equal(s.phase,'complete');assert.equal(s.notes.length,4);assert.equal(s.visited.length,4);});
test('all 40 questions require answers, explain mistakes, and separate sets with a blurb',()=>{const ids=new Set();let total=0;for(const leg of pack.legs){const r=createReview(leg,992);assert.equal(r.stage,'map');assert.equal(answerReview(r,0),null);assert(nextReview(r));assert.equal(nextReview(r),false);for(const stage of ['dock','camp']){assert.equal(r.stage,stage);assert.equal(r[stage].length,5);for(let i=0;i<5;i++){const q=reviewQuestion(r);assert(!ids.has(q.id));ids.add(q.id);assert(q.source&&q.verified&&q.explanation);const wrong=q.choices.find(c=>c.id!==q.correct);assert.equal(answerReview(r,wrong.id).correct,false);assert.equal(nextReview(r),false);assert.equal(answerReview(r,q.correct),null);assert.equal(r.hintOpen,true);dismissHint(r);assert.equal(answerReview(r,q.correct).correct,true);assert.equal(answerReview(r,q.correct),null);assert(nextReview(r));total++;}if(stage==='dock'){assert.equal(r.stage,'blurb');assert(leg.fieldNote.text.length>60);nextReview(r);}}assert.equal(r.stage,'done');assert.equal(r.correct,10);}assert.equal(total,40);});
test('release is standalone and has no runtime network calls',()=>{const h=readFileSync(new URL('../../../dist/River-Expedition-James-River.html',import.meta.url),'utf8');assert.doesNotMatch(h,/<(?:script|link|img|iframe)[^>]+(?:src|href)\s*=/i);assert.doesNotMatch(h,/\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/);assert.doesNotMatch(h,/\/\* (?:STYLES|GAME) \*\//);assert.match(h,/connect-src 'none'/);assert.match(h,/crypto.getRandomValues/);});
test('heart collectibles restore one, cannot exceed five, and cannot be reused',()=>{const s=createExpedition(pack);beginLeg(s,0);s.hazards=[];s.health=3;s.pickups=[{id:'heart',s:2,x:s.x,collected:false}];tick(s,{},1/60);assert.equal(s.health,4);assert(s.pickups[0].collected);tick(s,{},1/60);assert.equal(s.health,4);s.health=5;s.pickups=[{id:'full',s:s.progress+1,x:s.x,collected:false}];tick(s,{},1/60);assert.equal(s.health,5);assert(s.pickups[0].collected);});
test('heart placements are reachable and separated from hazards across 100 seeds',()=>{for(const leg of pack.legs)for(let seed=0;seed<100;seed++){const hazards=makeHazards(leg,seed),pickups=makePickups(leg,seed,hazards);assert.equal(pickups.length,leg.heartCount);assert.deepEqual(pickups,makePickups(leg,seed,hazards));for(const item of pickups){assert(item.s>200&&item.s<leg.length-100);for(const h of hazards)assert(Math.abs(item.s-h.s)>h.radius+32);const bank=riverProfile(leg,item.s);if(leg.mode==='boat')assert(item.x>bank.left+20&&item.x<bank.right-20);else assert(Math.abs(item.x-trailX(leg,item.s))<20);}}});
test('a hint does not advance progress and all choices remain valid on repeated retries',()=>{const r=createReview(pack.legs[0],17);nextReview(r);const q=reviewQuestion(r),wrong=q.choices.find(c=>c.id!==q.correct).id;for(let i=0;i<3;i++){const a=answerReview(r,wrong);assert.equal(a.text,q.hint);assert.notEqual(a.text,q.explanation);assert.equal(r.correct,0);assert.equal(r.index,0);assert.equal(nextReview(r),false);dismissHint(r);}answerReview(r,q.correct);assert.equal(r.correct,1);nextReview(r);assert.equal(r.index,1);});

test('curriculum items have four unique choices, regional alignment, sources, and hints without the answer',()=>{for(const l of pack.legs)for(const phase of ['dock','camp'])for(const q of l.questions[phase]){assert.equal(q.choices.length,4);assert.equal(new Set(q.choices).size,4);assert(q.standards.length&&q.region);assert(pack.questionSources[q.source]);assert.equal(q.itemType,'original-single-select');assert(!q.hint.toLowerCase().includes(q.choices[q.correct].toLowerCase()),q.id);assert.notEqual(q.source,'game');}});

test('all four trips have equal duration at neutral, boosted, slowed, and assisted pace',()=>{for(const assist of [false,true])for(const y of [-1,0,1]){const times=[];for(let i=0;i<pack.legs.length;i++){const s=createExpedition(pack,assist,99);beginLeg(s,i);s.hazards=[];s.pickups=[];s.invulnerable=1000;const l=currentLeg(s);let frames=0;while(s.phase==='play'&&frames++<10000){s.x=l.mode==='walk'?trailX(l,s.progress):riverProfile(l,s.progress).center;tick(s,{y},1/60);}assert.equal(s.phase,'docking');times.push(s.legTime);assert(Math.abs(s.legTime-75/((1-y*.24)*(assist?.8:1)))<.02);}assert(Math.max(...times)-Math.min(...times)<.02);}for(let i=1;i<4;i++){assert(pack.legs[i].speed>pack.legs[i-1].speed);assert(pack.legs[i].waterSaturation>pack.legs[i-1].waterSaturation);assert(pack.legs[i].hazardCount>pack.legs[i-1].hazardCount);}for(const l of pack.legs){const hs=makeHazards(l,3);for(let i=1;i<hs.length;i++)assert(hs[i].s-hs[i-1].s>=l.speed*1.24*1.4-.001);}});
