import {createExpedition,beginLeg,currentLeg,tick,advance,recover,WORLD} from './model.js';
import {createRenderer} from './render.js';
import {createInput} from './input.js';
import {createReview,reviewQuestion,answerReview,nextReview,dismissHint} from './review.js';
const $=id=>document.getElementById(id);
function freshSeed(){return crypto.getRandomValues(new Uint32Array(1))[0];}
const expedition=createExpedition(LEVEL,false,freshSeed());
const renderer=createRenderer($('game'),PIXELS);
const preferences={assist:false,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,touchControls:matchMedia('(pointer: coarse)').matches};
let toastUntil=0,overlayKind='title',returnPhase='play',review=null,oldHealth=null;
const controls=createInput($('game'),{onAction:()=>{},onPause:togglePause});
const safe=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

function referenceIcon(kind){return '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">'+(kind==='map'?'<path d="M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2V5zM9 3v16M15 5v16"/>':'<rect x="5" y="3" width="15" height="18" rx="2"/><path d="M8 3v18M3 7h4M3 12h4M3 17h4M11 8h6M11 12h6"/>')+'</svg>';}
function receivedNotes(){return LEVEL.legs.filter(l=>expedition.notes.some(n=>n.id===l.id)||(l.id===currentLeg(expedition).id&&review&&['blurb','camp','done'].includes(review.stage)));}
function locationStatus(){const leg=currentLeg(expedition);return expedition.visited.includes(leg.id)?leg.destination:expedition.visited.length?'Traveling toward '+leg.destination:'Starting on the James';}

function announce(){}
function showPanel(kind,html){controls.clear();overlayKind=kind;$('dialog').classList.toggle('hint-dialog',kind==='hint');$('dialog').innerHTML=html;const heading=$('dialog').querySelector('h1,h2');if(heading)heading.id='panelTitle';$('overlay').hidden=false;$('dialog').scrollTop=0;$('dialog').focus({preventScroll:true});setBackgroundInert(true);bindMapFacts();}
function setBackgroundInert(value){document.querySelector('.hud').inert=value;document.querySelector('.control-bar').inert=value;document.querySelector('.touch-row').inert=value;$('game').inert=value;}
function hidePanel(){controls.clear();$('overlay').hidden=true;overlayKind=null;setBackgroundInert(false);$('game').focus({preventScroll:true});}
function bind(id,fn){$(id)?.addEventListener('click',fn);}
function titleScreen(){expedition.phase='title';expedition.progress=900;expedition.hazards=[];
 showPanel('title',`<h1>River<span>Expedition</span></h1><button id="launch" class="gold wide">Play</button><button id="titleHelp" class="quiet wide">Controls</button><p class="game-credit">CCPS HSS Arcade</p>`);
 bind('launch',showIntroduction);bind('titleHelp',()=>showHelp('title'));
}
function showIntroduction(){
 showPanel('intro',`<h2>Up the James River</h2><p>Steer past branches, shallow water, and rocky outcrops. Reach each landing, discover its history, and make camp before heading onward.</p><div class="hazard-guide"><figure><canvas data-example="log" aria-label="Forked branch"></canvas><figcaption>Branches</figcaption></figure><figure><canvas data-example="shoal" aria-label="Pale shallow water"></canvas><figcaption>Shallows</figcaption></figure><figure><canvas data-example="rock" aria-label="Rocky outcrop"></canvas><figcaption>Rocks</figcaption></figure></div><p>Use the arrow keys or WASD, or hold the water to steer. Collect hearts to repair your boat.</p><button id="introNext" class="gold wide">Next →</button>`);
 document.querySelectorAll('[data-example]').forEach(canvas=>{canvas.width=96;canvas.height=64;const ctx=canvas.getContext('2d'),rows=PIXELS[canvas.dataset.example],scale=2;const width=Math.max(...rows.map(r=>r.length));rows.forEach((r,y)=>[...r].forEach((c,x)=>{if(PIXELS.palette[c]){ctx.fillStyle=PIXELS.palette[c];ctx.fillRect((96-width*scale)/2+x*scale,(64-rows.length*scale)/2+y*scale,scale,scale);}}));});
 bind('introNext',showQuestionIntroduction);
}
function showQuestionIntroduction(){showPanel('intro',`<h2>At each landing</h2><p>Answer five questions to dock, read your Field Note, then answer five more to make camp. Miss one? Use the hint and try again.</p><div class="reference-guide"><div>${referenceIcon('journal')}<p><strong>Journal</strong><br>Revisit Field Notes after you receive them. A grey notebook means none are available yet.</p></div><div>${referenceIcon('map')}<p><strong>Map</strong><br>Look for your flag. Tap a discovered place for a quick fact.</p></div></div><button id="beginRun" class="gold wide">Got it — let’s go!</button>`);bind('beginRun',()=>{expedition.assist=preferences.assist;beginLeg(expedition,0);hidePanel();updateUI();});}
function updateUI(){const leg=currentLeg(expedition);$('legNumber').textContent=expedition.phase==='title'?'YOUR NEXT ADVENTURE':`LEG ${expedition.legIndex+1} / ${LEVEL.legs.length} · ${leg.mode==='walk'?'ON FOOT':'PACE '+(expedition.legIndex+1)}`;$('legTitle').textContent=leg.name;$('modeLabel').textContent=leg.mode==='walk'?'SHORE TRAIL':'JAMES RIVER · '+(leg.tidal?'TIDAL WATER':'FALL LINE');$('objective').textContent=expedition.phase==='docking'?'Landing line crossed. Docking automatically…':expedition.progress>leg.length-250?leg.arrival:leg.objective;$('routeFill').style.width=Math.min(100,expedition.progress/leg.length*100)+'%';$('routeFill').parentElement.setAttribute('aria-label',`${Math.round(expedition.progress/leg.length*100)} percent to next stop`);$('touchControls').hidden=!preferences.touchControls;
 const healthKey=`${leg.mode}:${expedition.health}`;if(oldHealth!==healthKey){oldHealth=healthKey;$('hearts').innerHTML=`<span class="heart-symbols" aria-hidden="true">${'♥'.repeat(expedition.health)}<span class="empty-hearts">${'♡'.repeat(expedition.maxHealth-expedition.health)}</span></span><span class="heart-count">${leg.mode==='walk'?'CREW':'BOAT'} ${expedition.health}/${expedition.maxHealth}</span>`;$('hearts').setAttribute('aria-label',`${leg.mode==='walk'?'Crew energy':'Boat condition'}: ${expedition.health} of ${expedition.maxHealth} hearts`);}
}
function revealedPlaces(){return LEVEL.places.filter(p=>p.revealAt===null||expedition.visited.includes(p.revealAt));}
function atlasMarkup(){
 const project=([lon,lat])=>[(lon+77.85)*260,(37.96-lat)*328];
 const line=points=>points.map((p,i)=>(i?'L':'M')+project(p).map(n=>n.toFixed(1)).join(',')).join(' ');
 const polygons=features=>features.map(f=>{const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];return polys.map(p=>'<path d="'+p.map(r=>line(r)+'Z').join(' ')+'"/>').join('');}).join('');
 const rivers=HYDRO.rivers.map(f=>{const lines=f.geometry.type==='MultiLineString'?f.geometry.coordinates:[f.geometry.coordinates];return lines.map(p=>'<path d="'+line(p)+'"/>').join('');}).join('');
 const pins=revealedPlaces().map(p=>{const dot=project([p.lon,p.lat]),here=p.revealAt===currentLeg(expedition).id&&expedition.visited.includes(p.revealAt)||p.id==='bay'&&!expedition.visited.length;return '<button id="place-'+p.id+'" data-place="'+p.id+'" class="atlas-button pin-'+p.id+(here?' current-place':'')+'" aria-expanded="false" aria-controls="mapFact" aria-label="'+safe(p.name)+(here?', current stop':'')+': quick fact" style="left:'+dot[0]/5.6+'%;top:'+dot[1]/3.8+'%"><span class="pin-dot" aria-hidden="true"></span>'+(here?'<span class="location-flag" aria-hidden="true">⚑</span>':'')+'<span class="pin-label">'+(p.id==='bay'?'River mouth':p.id==='richmond'?'Richmond':safe(p.name))+'</span></button>';}).join('');
 return '<div class="atlas"><svg viewBox="0 0 560 380" role="img" aria-label="North-up map of the lower James River from Richmond past Jamestown to Chesapeake Bay. River bends are drawn from USGS hydrography."><rect width="560" height="380" fill="#b5d3d1"/><g fill="#d7d9ad" stroke="#91a887" stroke-width="1" fill-rule="evenodd">'+polygons(HYDRO.land)+'</g><g fill="#b5d3d1" stroke="#86b4b5" stroke-width="0.5" fill-rule="evenodd">'+polygons(HYDRO.water)+'</g><g fill="none" stroke="#397e8a" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round">'+rivers+'</g><g fill="#365958" font-family="Verdana,sans-serif"><text x="24" y="33" font-size="15">N ↑</text><text x="24" y="61" font-size="12" letter-spacing="2">VIRGINIA</text><text x="152" y="205" font-size="14" font-style="italic">James River</text><text x="455" y="135" font-size="12" transform="rotate(72 455 135)">Chesapeake Bay</text></g><path d="M25 345v5h59v-5" fill="none" stroke="#365958" stroke-width="2"/><text x="25" y="368" font-size="11" fill="#365958">20 km</text></svg>'+pins+'</div><p class="location-status"><span aria-hidden="true">⚑</span> '+safe(locationStatus())+'</p><div id="mapFact" class="map-fact" role="status" hidden></div>';
}
function bindMapFacts(){document.querySelectorAll('[data-place]').forEach(button=>button.addEventListener('click',()=>{const place=LEVEL.places.find(p=>p.id===button.dataset.place);const facts={bay:'The James River empties into the Chesapeake Bay, connecting inland communities with the Atlantic Ocean.',jamestown:'Jamestown lies on the James River in the Coastal Plain. Deep water let ships reach the settlement.',richmond:'At Richmond, the James crosses the Fall Line between the Piedmont and Coastal Plain. Rapids interrupted navigation.'};$('mapFact').hidden=false;$('mapFact').textContent=place.name+': '+facts[place.id];document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-expanded',String(b===button)));}));}
function openCheckpoint(){controls.clear();$('toast').hidden=true;review=createReview(currentLeg(expedition),expedition.seed+expedition.legIndex*137);showReview();}
function showDockMap(){const leg=currentLeg(expedition),fictional=['cargo','trail'].includes(leg.id);const diagram=fictional?`<svg class="dock-plan" viewBox="0 0 440 145" role="img" aria-label="Schematic of this fictional stop: river beside the landing and camp, not a geographic location."><rect width="200" height="145" fill="#377d80"/><rect x="200" width="240" height="145" fill="#a4bf8a"/><rect x="168" y="72" width="111" height="26" fill="#d59858"/><path d="M279 86 L340 86 L340 50" fill="none" stroke="#d59858" stroke-width="16"/><path d="M319 52 L340 22 L361 52Z" fill="#f2c66d" stroke="#172f36" stroke-width="3"/><text x="42" y="42">JAMES RIVER</text><text x="226" y="125">${leg.id==='trail'?'BASE CAMP':'SUPPLY LANDING'}</text></svg>`:atlasMarkup();showPanel('dock-map',`<h2>Welcome to ${safe(leg.id==='tidal'?'Jamestown':leg.id==='falls'?'Richmond':leg.id==='cargo'?'the supply landing':'base camp')}!</h2>${diagram}${fictional?'<p class="location-status">⚑ Current stop</p>':''}<p class="lead">${leg.mode==='walk'?'Let’s settle in.':'Let’s get you docked.'}</p><button id="beginDockQuestions" class="gold wide">Continue →</button>`);bind('beginDockQuestions',()=>{nextReview(review);showReview();});}
function showHint(){const q=reviewQuestion(review);showPanel('hint',`<h2>Take another look.</h2><p class="lead" id="hintText">${safe(q.hint)}</p><button id="retryQuestion" class="gold wide">Try again →</button>`);bind('retryQuestion',()=>{dismissHint(review);showReview();document.querySelector('[data-choice]')?.focus({preventScroll:true});});}

function fieldNoteMarkup(leg){const terms=[...(leg.fieldNote.keyTerms||[])].sort((a,b)=>b.length-a.length);let text=leg.fieldNote.text,out='';while(text.length){const lower=text.toLowerCase();let at=-1,term='';for(const t of terms){const found=lower.indexOf(t.toLowerCase());if(found>=0&&(at<0||found<at)){at=found;term=t;}}if(at<0){out+=safe(text);break;}out+=safe(text.slice(0,at))+'<mark><strong>'+safe(text.slice(at,at+term.length))+'</strong></mark>';text=text.slice(at+term.length);}return out;}
let closeReference=null;
function openQuestionReference(kind){if(kind==='journal'&&!receivedNotes().length)return;const dialog=$('dialog'),focus=document.activeElement,nodes=[...dialog.childNodes];showPanel('question-reference',`<h2>${kind==='journal'?'Field Notes':'Map'}</h2>${kind==='journal'?receivedNotes().map(l=>'<article class="journal-entry"><h3>'+safe(l.fieldNote.title)+'</h3><p>'+fieldNoteMarkup(l)+'</p></article>').reverse().join(''):atlasMarkup()}<button id="returnQuestion" class="gold wide">Back to question</button>`);closeReference=()=>{dialog.replaceChildren(...nodes);overlayKind='review';closeReference=null;focus?.focus({preventScroll:true});};bind('returnQuestion',()=>closeReference());}
function questionTools(){const locked=!receivedNotes().length;return '<nav class="question-tools" aria-label="Question references"><button id="questionJournal" class="quiet reference-icon" aria-label="'+(locked?'Field notes not received yet':'Open received field notes')+'" title="'+(locked?'Receive a Field Note to unlock':'Journal')+'" '+(locked?'disabled':'')+'>'+referenceIcon('journal')+'</button><button id="questionMap" class="quiet reference-icon" aria-label="Open map" title="Map">'+referenceIcon('map')+'</button></nav>';}

function showReview(){const leg=currentLeg(expedition);
 if(review.stage==='map'){showDockMap();return;}
 if(review.hintOpen){showHint();return;}
 if(review.stage==='blurb'){showPanel('review',`<span class="small-label">Field Note</span><h2>${safe(leg.fieldNote.title)}</h2><p class="lead">${fieldNoteMarkup(leg)}</p><button id="reviewNext" class="gold wide">Prepare camp for the night →</button>`);bind('reviewNext',()=>{nextReview(review);showReview();});return;}
 if(review.stage==='done'){continueJourney();return;}
 const q=reviewQuestion(review),dockSet=review.stage==='dock';
 showPanel('review',`${questionTools()}<h2>${safe(q.prompt)}</h2><div class="answers">${q.choices.map(c=>`<button class="answer" data-choice="${c.id}">${safe(c.text)}</button>`).join('')}</div><div id="checkpointFeedback" class="panel-feedback" role="status" hidden></div><button id="reviewNext" class="gold wide" hidden>${review.index===4?(dockSet?'Read the field note':'Make camp'):'Next question'} →</button>`);
 bind('questionJournal',()=>openQuestionReference('journal'));bind('questionMap',()=>openQuestionReference('map'));
 document.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>{const result=answerReview(review,Number(button.dataset.choice));if(!result)return;if(!result.correct){showHint();return;}$('checkpointFeedback').hidden=false;$('checkpointFeedback').textContent='✓ Correct. '+result.text;button.classList.add('correct');document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=true);$('reviewNext').hidden=false;$('reviewNext').focus({preventScroll:true});$('reviewNext').scrollIntoView({block:'nearest'});}));
 bind('reviewNext',()=>{nextReview(review);showReview();});
}
function continueJourney(){advance(expedition);review=null;if(expedition.phase==='complete'){showCamp();return;}hidePanel();updateUI();announce(currentLeg(expedition).objective);}
function journalMarkup(){return receivedNotes().length?receivedNotes().map(l=>`<article class="journal-entry"><h3>${safe(l.fieldNote.title)}</h3><p>${fieldNoteMarkup(l)}</p></article>`).join(''):'<p>No Field Notes received yet.</p>';}
function showCamp(){showPanel('complete',`<h2>Journey complete</h2>${journalMarkup()}<button id="replay" class="gold wide">Play again</button><button id="campMap" class="quiet wide">Map</button>`);bind('replay',restart);bind('campMap',()=>showMap('complete'));updateUI();}
function restart(){Object.assign(expedition,createExpedition(LEVEL,preferences.assist,freshSeed()));review=null;beginLeg(expedition,0);hidePanel();updateUI();announce('Fresh hazards, a fresh journey. Cross each landing line to dock automatically.');}
function pauseForPanel(){if(['play','docking'].includes(expedition.phase)){returnPhase=expedition.phase;expedition.phase='paused';}controls.clear();$('toast').hidden=true;}
function resume(){expedition.phase=returnPhase;hidePanel();updateUI();}
function showMap(back='play'){if(back==='play')pauseForPanel();const stops=LEVEL.legs.filter(l=>expedition.visited.includes(l.id));showPanel('map',`<h2>Map</h2>${atlasMarkup()}<p><strong>Stops reached:</strong> ${stops.length?stops.map(l=>safe(l.destination)).join(' · '):'None yet. Your starting point is marked.'}</p><p class="fine">The supply landing and base camp are fictional, so they have no geographic pins.</p><button id="back" class="gold wide">${back==='complete'?'Back to the journal':'Back to the river'}</button>`);bind('back',back==='complete'?showCamp:resume);}
function showJournal(){pauseForPanel();showPanel('journal',`<span class="small-label">FIELD NOTES</span><h2>Expedition journal</h2>${journalMarkup()}<button id="back" class="gold wide">Back to the river</button>`);bind('back',resume);}
function showHelp(back='play'){if(back==='play')pauseForPanel();showPanel('help',`<h2>Controls</h2><div class="keys"><b>← → / A D</b><span>Steer or walk sideways.</span><b>↑ / W</b><span>Move faster.</span><b>↓ / S</b><span>Move slower.</span><b>Mouse / touch</b><span>Hold the water to steer, or enable the directional pad below.</span><b>Landings</b><span>Your boat pulls in when you reach a landing.</span><b>P / Escape</b><span>Pause or resume. Map and Journal also pause travel.</span><b>♥ Hearts</b><span>A collision costs one heart, then gives you a brief recovery window. Collect floating hearts to restore one, up to five. Landings restore all five. At zero hearts, repair and resume nearby—no game over. On foot, hearts represent crew energy.</span></div><label><input id="assist" type="checkbox" ${preferences.assist?'checked':''}>Gentle pace</label><label><input id="reduced" type="checkbox" ${preferences.reducedMotion?'checked':''}>Reduce decorative motion. Necessary navigation scrolling remains.</label><label><input id="showTouch" type="checkbox" ${preferences.touchControls?'checked':''}>Show on-screen directional controls.</label><p class="fine">Every launch or replay gets a new random seed. Later water legs are longer and faster. Questions never cost hearts. Progress is not saved after reload. Seed for reproducing this run: ${expedition.seed}.</p><button id="back" class="gold wide">${back==='title'?'Back to launch':'Back to the river'}</button>`);$('assist').onchange=e=>{preferences.assist=e.target.checked;expedition.assist=preferences.assist;};$('reduced').onchange=e=>preferences.reducedMotion=e.target.checked;$('showTouch').onchange=e=>{preferences.touchControls=e.target.checked;updateUI();};bind('back',back==='title'?titleScreen:resume);}
function showRescue(){controls.clear();$('toast').hidden=true;showPanel('rescue',`<h2>${currentLeg(expedition).mode==='walk'?'Take a rest':'Repair your boat'}</h2><button id="recover" class="gold wide">Continue</button>`);bind('recover',()=>{recover(expedition);hidePanel();updateUI();});}
function togglePause(){if(closeReference){closeReference();return;}if(expedition.phase==='paused'&&['help','map','journal'].includes(overlayKind)){resume();return;}if(overlayKind==='pause'){resume();return;}if(!['play','docking'].includes(expedition.phase))return;pauseForPanel();showPanel('pause',`<h2>Paused</h2><button id="resume" class="gold wide">Resume</button><button id="restartRequest" class="quiet wide">Restart</button>`);bind('resume',resume);bind('restartRequest',()=>{showPanel('restart',`<h2>Restart?</h2><p>Start over from the beginning?</p><div class="panel-actions"><button id="confirmRestart" class="gold">Restart</button><button id="cancelRestart">Keep this expedition</button></div>`);bind('confirmRestart',restart);bind('cancelRestart',resume);});}
bind('pauseButton',togglePause);bind('mapButton',()=>showMap());bind('journalButton',showJournal);bind('helpButton',()=>showHelp());
window.addEventListener('blur',()=>{if(['play','docking'].includes(expedition.phase))togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['play','docking'].includes(expedition.phase))togglePause();});
$('dialog').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const focusable=[...$('dialog').querySelectorAll('button,input,[tabindex="0"]')].filter(el=>!el.disabled&&!el.hidden&&!el.closest('[hidden]'));if(!focusable.length){e.preventDefault();return;}const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('dialog'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===$('dialog'))){e.preventDefault();first.focus();}});
let last=performance.now(),accumulator=0,uiClock=0,visualTime=0;
function frame(now){const delta=Math.min((now-last)/1000,.1);last=now;accumulator+=delta;if(['play','docking'].includes(expedition.phase))visualTime+=delta;
 while(accumulator>=WORLD.step){tick(expedition,controls.read(expedition.x),WORLD.step);for(const event of expedition.events.splice(0)){if(event.type==='arrival')openCheckpoint();else if(event.type==='rescue')showRescue();else announce(event.text,event.type);}accumulator-=WORLD.step;}
 uiClock+=delta;if(uiClock>.1){updateUI();uiClock=0;}renderer.render(expedition,visualTime,preferences.reducedMotion);if(now>toastUntil)$('toast').hidden=true;requestAnimationFrame(frame);
}
titleScreen();requestAnimationFrame(frame);

